### ISSUE TITLE
Excon  Timeout error is not properly handled

### ISSUE THREAD

**Issue by bogdan** [dandemeyere/responsys-api#32]
``` 
bundler/gems/responsys-api-d9498c2ca06a/lib/responsys/helper.rb:68:in `format_response_with_errors': undefined method `to_hash' for #<Excon::Errors::Timeout: read timeout reached> (NoMethodError)
	from bundler/gems/responsys-api-d9498c2ca06a/lib/responsys/api/client.rb:45:in `rescue in api_method'
	from bundler/gems/responsys-api-d9498c2ca06a/lib/responsys/api/client.rb:34:in `api_method'
	from bundler/gems/responsys-api-d9498c2ca06a/lib/responsys/api/list.rb:15:in `retrieve_list_members'
```

**Comment by florrain** [comment]
A fix to handle those would be great. If you're willing to help feel free to write here to discuss it. 

Also, this might be resolved when we go REST soon(ish).
